[package]
name = "vpk0"
version = "0.8.0"
authors = ["tehzz"]
edition = "2018"

[dependencies]
bitstream-io = "0.8.2"
slice-deque = "0.3.0"
err-derive = "0.2.3"
smallvec = {version = "1.6.1", features = ["union"]}
